apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tteqevfrp-java-springboot-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/tteqevfrp-java-springboot-gitops